name: photoline
description: Photoline plugin.
version: 1.0.3
homepage: https://github.com/nazarpunk/flutter-photoline

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.1.0
